"""
repositories/department_repository.py
---------------------------------------
Purpose:
    The Repository layer is the ONLY place in the application allowed
    to write raw SQL. It talks directly to SQLite and converts rows
    into Department model objects (and vice versa).

Why this file exists:
    Separating SQL from business logic (services) means the database
    can change (e.g. SQLite -> PostgreSQL) without touching the service
    or controller layers — only this file would need to change.

How it communicates with the next layer:
    - Downward: uses config/database.get_connection() to talk to SQLite.
    - Upward: returns Department model objects to department_service.py.
"""

from typing import List, Optional

from config.database import get_connection
from models.department import Department


class DepartmentRepository:
    """Handles all direct database access for the department table."""

    def add(self, department: Department) -> Department:
        """
        Insert a new department row into the database.

        Args:
            department (Department): Department object without an id
                (department_id is assigned by SQLite on insert).

        Returns:
            Department: The same department, now populated with the
            department_id generated by SQLite.
        """
        connection = get_connection()
        try:
            cursor = connection.execute(
                """
                INSERT INTO department (department_name, hod_name)
                VALUES (?, ?)
                """,
                (department.department_name, department.hod_name),
            )
            connection.commit()
            department.department_id = cursor.lastrowid
            return department
        finally:
            connection.close()

    def get_by_id(self, department_id: int) -> Optional[Department]:
        try:
            connection = get_connection()
            cursor = connection.execute(
                "SELECT * FROM department WHERE department_id = ?",
                (department_id,),
            )
            row = cursor.fetchone()
            if row:
                return Department(
                    department_id=row[0], department_name=row[1], hod_name=row[2]
                )
            else:
                return None
        finally:
            connection.close()

    def get_all(self) -> List[Department]:
        try:
            connection = get_connection()
            cursor = connection.execute("SELECT * FROM department")
            rows = cursor.fetchall()
            return [
                Department(
                    department_id=row[0], department_name=row[1], hod_name=row[2]
                )
                for row in rows
            ]
        finally:
            connection.close()

    def update(self, department: Department) -> bool:
        try:
            connection = get_connection()
            cursor = connection.execute(
                """
                UPDATE department
                SET department_name = ?, hod_name = ?
                WHERE department_id = ?
                """,
                (department.department_name, department.hod_name, department.department_id),
            )
            connection.commit()
            return cursor.rowcount > 0
        finally:
            connection.close()

    def delete(self, department_id: int) -> bool:
        try:
            connection = get_connection()
            cursor = connection.execute(
                "DELETE FROM department WHERE department_id = ?",
                (department_id,),
            )
            connection.commit()
            return cursor.rowcount > 0
        finally:
            connection.close()
