"""
repositories/department_repository.py
---------------------------------------
Purpose:
    The Repository layer is the ONLY place in the application allowed
    to write raw SQL. It talks directly to SQLite and converts rows
    into Department model objects (and vice versa).

Why this file exists:
    Separating SQL from business logic (services) means the database
    can change (e.g. SQLite -> PostgreSQL) without touching the service
    or controller layers — only this file would need to change.

How it communicates with the next layer:
    - Downward: uses config/database.get_connection() to talk to SQLite.
    - Upward: returns Department model objects to department_service.py.
"""

from typing import List, Optional

from config.database import get_connection
from models.department import Department


class DepartmentRepository:
    """Handles all direct database access for the department table."""

    def add(self, department: Department) -> Department:
        """
        Insert a new department row into the database.

        Args:
            department (Department): Department object without an id
                (department_id is assigned by SQLite on insert).

        Returns:
            Department: The same department, now populated with the
            department_id generated by SQLite.
        """
        connection = get_connection()
        try:
            cursor = connection.execute(
                """
                INSERT INTO department (department_name, hod_name)
                VALUES (?, ?)
                """,
                (department.department_name, department.hod_name),
            )
            connection.commit()
            department.department_id = cursor.lastrowid
            return department
        finally:
            connection.close()

    def get_by_id(self, department_id: int) -> Optional[Department]:
        """
        TODO (Student Exercise):
        Fetch a single department row by its primary key and map it to
        a Department object. Return None if no row is found.

        Hint:
            SELECT * FROM department WHERE department_id = ?
        """
        raise NotImplementedError("Students will implement this feature.")

    def get_all(self) -> List[Department]:
        """
        TODO (Student Exercise):
        Fetch every row from the department table and return a list of
        Department objects.

        Hint:
            SELECT * FROM department ORDER BY department_id
        """
        raise NotImplementedError("Students will implement this feature.")

    def update(self, department: Department) -> bool:
        """
        TODO (Student Exercise):
        Update department_name and hod_name for the row matching
        department.department_id. Return True if a row was updated.

        Hint:
            UPDATE department SET department_name = ?, hod_name = ?
            WHERE department_id = ?
        """
        raise NotImplementedError("Students will implement this feature.")

    def delete(self, department_id: int) -> bool:
        """
        TODO (Student Exercise):
        Delete the department row matching department_id. Return True
        if a row was deleted.

        Hint:
            DELETE FROM department WHERE department_id = ?

        Note: Because of the foreign key constraint, deleting a
        department that still has students/staff assigned to it will
        fail. Think about how you want to handle that case.
        """
        raise NotImplementedError("Students will implement this feature.")
